services:
  - type: web
    name: neuroview-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT run:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
